language: php

php:
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer install -o

services:
  - mysql

before_script:
  - mysql -e 'create database mail_queue_test;'

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
